---
# This playbook deploys the whole application stack in this site.

- name: Install Modsecurity
  hosts: modsec
  remote_user: centos
  become: yes
  become_method: sudo

  roles:
    - sardpost.modsecurity
    - yaegashi.blockinfile
